import type { Product } from "@/types";

const products: Product[] = [
  {
    id: "shadow-tee",
    name: "Shadow Graphic Tee",
    description: "Algodón pesado · fit oversize",
    longDescription: "Polo de algodón premium de 280 gramos, hombro caído y gráfico de edición limitada. Una base sólida para cualquier rotación urbana.",
    price: 129,
    badge: "MÁS VENDIDO",
    category: "Essential Oversize",
    type: "Polo",
    sizes: ["S", "M", "L", "XL"],
    colors: ["Negro", "Blanco"],
    spritePosition: "0% 0%",
    imageAlt: "Polo negro oversize con gráfico abstracto",
  },
  {
    id: "washed-denim",
    name: "Washed Denim Jacket",
    description: "Denim lavado · corte relajado",
    longDescription: "Chaqueta de denim rígido con lavado azul vintage, silueta amplia y costuras reforzadas. Diseñada para llevar sobre cualquier capa.",
    price: 249,
    badge: "NUEVO",
    category: "Denim & Cargo",
    type: "Chaqueta",
    sizes: ["S", "M", "L", "XL"],
    colors: ["Azul lavado"],
    spritePosition: "50% 0%",
    imageAlt: "Chaqueta de denim azul lavado",
  },
  {
    id: "utility-cargo",
    name: "Utility Cargo 02",
    description: "Sarga resistente · pierna amplia",
    longDescription: "Cargo de tiro medio con bolsillos utilitarios, ajuste relajado y sarga resistente. Comodidad real sin perder estructura.",
    price: 189,
    badge: "MÁS VENDIDO",
    category: "Denim & Cargo",
    type: "Pantalón",
    sizes: ["S", "M", "L", "XL"],
    colors: ["Negro", "Gris carbón"],
    spritePosition: "100% 0%",
    imageAlt: "Pantalón cargo negro de pierna amplia",
  },
  {
    id: "bone-hoodie",
    name: "Bone Heavy Hoodie",
    description: "Felpa premium · 480 gramos",
    longDescription: "Hoodie pesado con interior suave, capucha estructurada y acabado color hueso. Volumen preciso para usar solo o en capas.",
    price: 219,
    badge: "NUEVO",
    category: "Core Neutrals",
    type: "Hoodie",
    sizes: ["S", "M", "L", "XL"],
    colors: ["Hueso", "Gris carbón"],
    spritePosition: "0% 100%",
    imageAlt: "Hoodie color crema de corte amplio",
  },
  {
    id: "night-bomber",
    name: "Night Bomber",
    description: "Nylon mate · relleno ligero",
    longDescription: "Bomber de nylon mate repelente al agua con relleno ligero y herrajes oscuros. Una capa funcional para después del atardecer.",
    price: 289,
    badge: "ÚLTIMAS UNIDADES",
    category: "After Dark",
    type: "Chaqueta",
    sizes: ["S", "M", "L", "XL"],
    colors: ["Negro"],
    spritePosition: "50% 100%",
    imageAlt: "Chaqueta bomber negra de nylon",
  },
  {
    id: "blank-tee",
    name: "Blank Tee White",
    description: "Algodón peinado · boxy fit",
    longDescription: "Polo blanco de algodón peinado, cuello compacto y corte boxy. Un esencial limpio pensado para repetir toda la semana.",
    price: 99,
    badge: "NUEVO",
    category: "Core Neutrals",
    type: "Polo",
    sizes: ["S", "M", "L", "XL"],
    colors: ["Blanco", "Negro"],
    spritePosition: "100% 100%",
    imageAlt: "Polo blanco liso de corte boxy",
  },
];

export function getCatalogProducts(): Product[] {
  return products;
}
